/**
 * Suggestion lists for the NDA form's location fields. These back native
 * `<datalist>` autocompletes — they are hints only; any free-text value is
 * still accepted.
 */

/** US states + DC, for the "Governing law" field. */
export const US_STATES: readonly string[] = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "District of Columbia",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];

/**
 * Common commercial-contract venues ("City, State"), for the "Jurisdiction"
 * field. Not exhaustive — the field accepts any text.
 */
export const COMMON_JURISDICTIONS: readonly string[] = [
  "New Castle, Delaware",
  "Wilmington, Delaware",
  "New York, New York",
  "San Francisco, California",
  "Santa Clara, California",
  "Los Angeles, California",
  "San Diego, California",
  "Seattle, Washington",
  "Chicago, Illinois",
  "Boston, Massachusetts",
  "Austin, Texas",
  "Dallas, Texas",
  "Houston, Texas",
  "Denver, Colorado",
  "Atlanta, Georgia",
  "Miami, Florida",
  "Minneapolis, Minnesota",
  "Portland, Oregon",
  "Nashville, Tennessee",
  "Charlotte, North Carolina",
  "Newark, New Jersey",
  "Philadelphia, Pennsylvania",
  "Pittsburgh, Pennsylvania",
  "Phoenix, Arizona",
  "Salt Lake City, Utah",
  "Las Vegas, Nevada",
  "Detroit, Michigan",
  "Columbus, Ohio",
  "Washington, District of Columbia",
];
